# Generated by Django 3.2.7 on 2021-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, choices=[('0', 'Русский'), ('1', 'Українська'), ('2', 'Беларуская'), ('3', 'English')], max_length=10, verbose_name='язык'),
        ),
    ]
